// --- GAME CONFIGURATION ---
export const gameConfig = {
    maxLives: 3,
    timerDuration: 15,
    basePoints: 100,
    timeBonusMultiplier: 10,
    streakBonusMultiplier: 50,
    questionsPerSession: Infinity, // Survival mode - no limit
    defaultMode: 'survival' // 'survival' or 'fixed'
};

// --- DATA: 100 QUESTIONS ---
export const allQuestionsDB = [
    // SCIENCE (20)
    { q: "Apa simbol kimia untuk Emas?", options: ["Au", "Ag", "Fe", "Go"], correct: 0, category: "Science" },
    { q: "Apakah pembangkit tenaga listrik sel?", options: ["Nukleus", "Ribosom", "Mitokondria", "Sitoplasma"], correct: 2, category: "Science" },
    { q: "Gas apa yang diserap tanaman dari atmosfer?", options: ["Oksigen", "Nitrogen", "Karbon Dioksida", "Hidrogen"], correct: 2, category: "Science" },
    { q: "Apa zat alami paling keras di Bumi?", options: ["Emas", "Besi", "Berlian", "Platinum"], correct: 2, category: "Science" },
    { q: "Berapa kecepatan cahaya?", options: ["300.000 km/s", "150.000 km/s", "1.000 km/s", "3.000 km/s"], correct: 0, category: "Science" },
    { q: "Berapa banyak tulang dalam tubuh manusia dewasa?", options: ["200", "206", "212", "190"], correct: 1, category: "Science" },
    { q: "Apa rumus kimia untuk garam meja?", options: ["H2O", "NaCl", "CO2", "KCl"], correct: 1, category: "Science" },
    { q: "Planet mana yang memiliki bulan terbanyak?", options: ["Jupiter", "Saturnus", "Mars", "Neptunus"], correct: 1, category: "Science" },
    { q: "Apa nama ilmu yang mempelajari jamur?", options: ["Botani", "Mikologi", "Zoologi", "Virologi"], correct: 1, category: "Science" },
    { q: "Bagian tanaman apa yang melakukan fotosintesis?", options: ["Akar", "Batang", "Daun", "Bunga"], correct: 2, category: "Science" },
    { q: "Apa tulang terkecil dalam tubuh manusia?", options: ["Stapes", "Femur", "Humerus", "Tibia"], correct: 0, category: "Science" },
    { q: "Gas apa yang paling melimpah di atmosfer bumi?", options: ["Oksigen", "Nitrogen", "Argon", "Karbon Dioksida"], correct: 1, category: "Science" },
    { q: "Berapakah titik lebur es?", options: ["0°C", "32°F", "Keduanya Benar", "100°C"], correct: 2, category: "Science" },
    { q: "Organ mana yang memompa darah ke seluruh tubuh?", options: ["Paru-paru", "Hati", "Jantung", "Otak"], correct: 2, category: "Science" },
    { q: "Berapakah nomor atom Karbon?", options: ["6", "12", "8", "14"], correct: 0, category: "Science" },
    { q: "Hukum Gerak Pertama Newton juga dikenal sebagai?", options: ["Hukum Gaya", "Hukum Inersia", "Hukum Gravitasi", "Hukum Gerak"], correct: 1, category: "Science" },
    { q: "Apa organ terbesar dalam tubuh manusia?", options: ["Hati", "Kulit", "Jantung", "Paru-paru"], correct: 1, category: "Science" },
    { q: "Vitamin mana yang diproduksi oleh tubuh saat terkena sinar matahari?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], correct: 2, category: "Science" },
    { q: "Apa simbol kimia untuk Oksigen?", options: ["O", "Ox", "O2", "O3"], correct: 0, category: "Science" },
    { q: "Golongan darah mana yang menjadi donor universal?", options: ["Golongan A", "Golongan B", "Golongan AB", "Golongan O Negatif"], correct: 3, category: "Science" },

    // TECHNOLOGY (20)
    { q: "Apa kepanjangan dari CPU?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Process Unit", "Central Processor United"], correct: 0, category: "Technology" },
    { q: "Siapa pendiri Microsoft?", options: ["Steve Jobs", "Bill Gates", "Elon Musk", "Mark Zuckerberg"], correct: 1, category: "Technology" },
    { q: "Apa kepanjangan dari HTML?", options: ["Hyper Text Markup Language", "High Tech Made Language", "Hyperlink Text Mark Language", "Home Tool Markup Language"], correct: 0, category: "Technology" },
    { q: "Perangkat mana yang digunakan untuk memasukkan data ke komputer?", options: ["Monitor", "Printer", "Keyboard", "Speaker"], correct: 2, category: "Technology" },
    { q: "Apa 'otak' dari sebuah komputer?", options: ["RAM", "Hard Drive", "CPU", "GPU"], correct: 2, category: "Technology" },
    { q: "Apa kepanjangan dari URL?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Universal Reference Link", "Uniform Reference Locator"], correct: 1, category: "Technology" },
    { q: "Bahasa pemrograman mana yang dikenal sebagai 'bahasa web'?", options: ["Python", "Java", "JavaScript", "C++"], correct: 2, category: "Technology" },
    { q: "Apa itu gigabyte (GB)?", options: ["1000 bytes", "1000 megabytes", "1024 megabytes", "100 kilobytes"], correct: 2, category: "Technology" },
    { q: "Siapa yang mendirikan Apple Computer?", options: ["Bill Gates", "Steve Jobs & Wozniak", "Mark Zuckerberg", "Larry Page"], correct: 1, category: "Technology" },
    { q: "Apa fungsi utama dari sistem operasi?", options: ["Main games", "Mengelola hardware dan software", "Membuat dokumen", "Browse internet"], correct: 1, category: "Technology" },
    { q: "Apa kepanjangan dari RAM?", options: ["Read Access Memory", "Random Access Memory", "Run All Memory", "Random Automated Module"], correct: 1, category: "Technology" },
    { q: "Komponen mana yang digunakan untuk menyimpan data secara permanen?", options: ["RAM", "Cache", "Hard Drive", "CPU"], correct: 2, category: "Technology" },
    { q: "Apa itu alamat IP?", options: ["Internet Provider Address", "Internet Protocol Address", "Internal Portal Address", "Internet Personal Address"], correct: 1, category: "Technology" },
    { q: "Perusahaan mana yang membuat PlayStation?", options: ["Microsoft", "Nintendo", "Sony", "Sega"], correct: 2, category: "Technology" },
    { q: "Apa kepanjangan dari 'www'?", options: ["World Web Wide", "World Wide Web", "Wide World Web", "Web World Wide"], correct: 1, category: "Technology" },
    { q: "Bahasa apa yang digunakan untuk membuat gaya tampilan web?", options: ["HTML", "CSS", "Python", "Java"], correct: 1, category: "Technology" },
    { q: "Apa pintasan untuk 'Copy' di keyboard?", options: ["Ctrl + V", "Ctrl + X", "Ctrl + C", "Ctrl + P"], correct: 2, category: "Technology" },
    { q: "Apa kepanjangan dari AI?", options: ["Automated Intelligence", "Artificial Intelligence", "Advanced Integration", "Automatic Image"], correct: 1, category: "Technology" },
    { q: "Perangkat mana yang mengubah sinyal digital menjadi analog untuk transmisi suara?", options: ["Modem", "Router", "Switch", "Hub"], correct: 0, category: "Technology" },
    { q: "Apa kode biner untuk angka 2?", options: ["01", "10", "11", "00"], correct: 1, category: "Technology" },

    // GEOGRAPHY (20)
    { q: "Apa samudra terbesar di Bumi?", options: ["Atlantik", "Hindia", "Pasifik", "Arktik"], correct: 2, category: "Geography" },
    { q: "Negara mana yang memiliki populasi terbanyak?", options: ["USA", "India", "China", "Rusia"], correct: 1, category: "Geography" },
    { q: "Apa ibu kota negara Prancis?", options: ["London", "Berlin", "Paris", "Madrid"], correct: 2, category: "Geography" },
    { q: "Benua mana yang dikenal sebagai 'Benua Hitam'?", options: ["Asia", "Afrika", "Australia", "Amerika Selatan"], correct: 1, category: "Geography" },
    { q: "Sungai terpanjang di dunia adalah?", options: ["Amazon", "Nil", "Yangtze", "Mississippi"], correct: 1, category: "Geography" },
    { q: "Gurun mana yang terbesar di dunia?", options: ["Gobi", "Sahara", "Arabia", "Antarktika"], correct: 3, category: "Geography" },
    { q: "Apa ibu kota Jepang?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correct: 2, category: "Geography" },
    { q: "Negara mana yang bentuknya seperti sepatu bot?", options: ["Spanyol", "Italia", "Yunani", "Turki"], correct: 1, category: "Geography" },
    { q: "Negara terkecil di dunia adalah?", options: ["Monako", "Vatikan", "San Marino", "Liechtenstein"], correct: 1, category: "Geography" },
    { q: "Gunung Everest terletak di pegunungan mana?", options: ["Alpen", "Andes", "Rocky", "Himalaya"], correct: 3, category: "Geography" },
    { q: "Apa ibu kota Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2, category: "Geography" },
    { q: "Sungai mana yang mengalir melalui London?", options: ["Seine", "Thames", "Rhine", "Danube"], correct: 1, category: "Geography" },
    { q: "Apa ibu kota Amerika Serikat?", options: ["New York", "Los Angeles", "Washington D.C.", "Chicago"], correct: 2, category: "Geography" },
    { q: "Planet mana yang dikenal sebagai Planet Merah?", options: ["Venus", "Jupiter", "Mars", "Saturnus"], correct: 2, category: "Geography" },
    { q: "Negara mana yang dijuluki Negeri Matahari Terbit?", options: ["China", "Jepang", "Korea Selatan", "Vietnam"], correct: 1, category: "Geography" },
    { q: "Pulau terbesar di dunia adalah?", options: ["Madagaskar", "Greenland", "Borneo", "Papua Nugini"], correct: 1, category: "Geography" },
    { q: "Di kota mana Menara Eiffel berada?", options: ["Roma", "Berlin", "Paris", "Wina"], correct: 2, category: "Geography" },
    { q: "Apa ibu kota Kanada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2, category: "Geography" },
    { q: "Negara mana yang menjadi rumah bagi Hutan Hujan Amazon?", options: ["Argentina", "Brazil", "Kolombia", "Peru"], correct: 1, category: "Geography" },
    { q: "Air terjun tertinggi di dunia adalah?", options: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"], correct: 2, category: "Geography" },

    // HISTORY (20)
    { q: "Siapa Presiden pertama Amerika?", options: ["Abraham Lincoln", "Thomas Jefferson", "George Washington", "John Adams"], correct: 2, category: "History" },
    { q: "Pada tahun berapa Perang Dunia II berakhir?", options: ["1940", "1942", "1945", "1949"], correct: 2, category: "History" },
    { q: "Siapa yang menemukan Amerika tahun 1492?", options: ["Amerigo Vespucci", "Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama"], correct: 1, category: "History" },
    { q: "Kekaisaran mana yang membangun Colosseum?", options: ["Yunani", "Romawi", "Mesir", "Persia"], correct: 1, category: "History" },
    { q: "Siapa yang melukis Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correct: 2, category: "History" },
    { q: "Apa nama kapal yang tenggelam tahun 1912?", options: ["Lusitania", "Titanic", "Olympic", "Britannic"], correct: 1, category: "History" },
    { q: "Siapa manusia pertama yang menginjak bulan?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], correct: 1, category: "History" },
    { q: "Di negara mana Revolusi Industri dimulai?", options: ["USA", "Prancis", "Jerman", "Inggris Raya"], correct: 3, category: "History" },
    { q: "Siapa penulis Deklarasi Kemerdekaan?", options: ["Benjamin Franklin", "Thomas Jefferson", "George Washington", "John Hancock"], correct: 1, category: "History" },
    { q: "Tembok Besar berada di negara mana?", options: ["Jepang", "China", "Mongolia", "India"], correct: 1, category: "History" },
    { q: "Siapa yang dijuluki 'Putri Orleans'?", options: ["Marie Curie", "Joan of Arc", "Ratu Victoria", "Cleopatra"], correct: 1, category: "History" },
    { q: "Peradaban kuno mana yang membangun Machu Picchu?", options: ["Maya", "Aztec", "Inca", "Olmec"], correct: 2, category: "History" },
    { q: "Siapa Perdana Menteri wanita pertama di Inggris?", options: ["Theresa May", "Margaret Thatcher", "Ratu Elizabeth I", "Ratu Victoria"], correct: 1, category: "History" },
    { q: "Tahun berapa Tembok Berlin runtuh?", options: ["1987", "1989", "1991", "1985"], correct: 1, category: "History" },
    { q: "Siapa Kaisar Prancis yang dikalahkan di Waterloo?", options: ["Louis XIV", "Napoleon Bonaparte", "Charlemagne", "Robespierre"], correct: 1, category: "History" },
    { q: "Tahun berapa iPhone pertama dirilis?", options: ["2005", "2006", "2007", "2008"], correct: 2, category: "History" },
    { q: "Siapa penemu telepon?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correct: 1, category: "History" },
    { q: "Siapa penguasa Inggris terlama?", options: ["Victoria", "Elizabeth II", "Henry VIII", "George III"], correct: 1, category: "History" },
    { q: "Peradaban mana yang membangun piramida?", options: ["Romawi", "Yunani", "Mesir", "Sumeria"], correct: 2, category: "History" },
    { q: "Peristiwa apa yang memicu Perang Dunia I?", options: ["Invasi ke Polandia", "Pembunuhan Archduke Ferdinand", "Pengeboman Pearl Harbor", "Perjanjian Versailles"], correct: 1, category: "History" },

    // GENERAL (20)
    { q: "Berapa banyak warna dalam pelangi?", options: ["5", "6", "7", "8"], correct: 2, category: "General" },
    { q: "Apa hewan nasional Amerika?", options: ["Bald Eagle", "Beruang", "Serigala", "Singa"], correct: 0, category: "General" },
    { q: "Buah apa yang terkenal mengusir dokter?", options: ["Jeruk", "Pisang", "Apel", "Anggur"], correct: 2, category: "General" },
    { q: "Berapa huruf dalam alfabet Inggris?", options: ["24", "25", "26", "27"], correct: 2, category: "General" },
    { q: "Mata uang apa yang digunakan di Jepang?", options: ["Yuan", "Won", "Yen", "Dolar"], correct: 2, category: "General" },
    { q: "Berapa sisi segi enam?", options: ["5", "6", "7", "8"], correct: 1, category: "General" },
    { q: "Olahraga apa yang dipertandingkan di Wimbledon?", options: ["Golf", "Cricket", "Tenis", "Rugby"], correct: 2, category: "General" },
    { q: "Apa hewan darat terbesar?", options: ["Gajah", "Badak", "Jerapah", "Kuda Nil"], correct: 0, category: "General" },
    { q: "Siapa yang melukis Pinokio dalam cerita?", options: ["Gepetto", "Peri Biru", "Stromboli", "Jiminy Cricket"], correct: 0, category: "General" },
    { q: "Berapa pemain dalam satu tim sepak bola?", options: ["9", "10", "11", "12"], correct: 2, category: "General" },
    { q: "Bahan utama Guacamole adalah?", options: ["Tomat", "Bawang", "Alpukat", "Cabai"], correct: 2, category: "General" },
    { q: "Tanda zodiak apa yang dilambangkan dengan Banteng?", options: ["Aries", "Taurus", "Gemini", "Leo"], correct: 1, category: "General" },
    { q: "Batu apa yang paling keras?", options: ["Berlian", "Granit", "Marmer", "Kuarsa"], correct: 0, category: "General" },
    { q: "Negara mana yang memberikan Patung Liberty ke Amerika?", options: ["Inggris", "Prancis", "Jerman", "Spanyol"], correct: 1, category: "General" },
    { q: "Apa nama peri dalam Peter Pan?", options: ["Silvermist", "Rosetta", "Tinker Bell", "Fawn"], correct: 2, category: "General" },
    { q: "Berapa tuts pada piano standar?", options: ["86", "88", "90", "92"], correct: 1, category: "General" },
    { q: "Hewan tercepat di darat adalah?", options: ["Singa", "Cheetah", "Kuda", "Macan Tutul"], correct: 1, category: "General" },
    { q: "Apa nama anak anjing?", options: ["Anak Kucing", "Anak Anjing", "Anak Harimau", "Anak Sapi"], correct: 1, category: "General" },
    { q: "Siapa pahlawan super Bruce Wayne?", options: ["Superman", "Iron Man", "Batman", "Flash"], correct: 2, category: "General" },
    { q: "Berapa hari dalam tahun kabisat?", options: ["364", "365", "366", "367"], correct: 2, category: "General" }
];

export const opponents = [
    { name: "CyberWolf", score: 800, streak: 2, avatar: "🐺" },
    { name: "NeonNinja", score: 750, streak: 0, avatar: "🥷" },
    { name: "PixelQueen", score: 680, streak: 1, avatar: "👸" },
    { name: "BitMaster", score: 500, streak: 0, avatar: "🤖" },
    { name: "GlitchX", score: 420, streak: 3, avatar: "👾" },
    { name: "DataValk", score: 300, streak: 0, avatar: "🛡️" },
    { name: "StarFox", score: 250, streak: 0, avatar: "🦊" },
    { name: "ByteStorm", score: 180, streak: 1, avatar: "⚡" },
    { name: "PixelPilot", score: 120, streak: 0, avatar: "✈️" },
    { name: "CyberGhost", score: 50, streak: 0, avatar: "👻" },
];
