-- ============================================
-- FIX SUPABASE TABLE FOR SCORE SAVING
-- ============================================
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================

-- 1. Drop existing table if exists (to recreate fresh)
DROP TABLE IF EXISTS scores CASCADE;

-- 2. Create scores table with correct structure
CREATE TABLE scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL,
    score INTEGER NOT NULL,
    streak INTEGER NOT NULL DEFAULT 0,
    avatar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies to allow anonymous users
--    This is CRITICAL for the game to work with anon key!

-- Policy: Allow anonymous users to INSERT new scores
CREATE POLICY "Allow anonymous inserts"
ON scores
FOR INSERT
TO anon
WITH CHECK (true);

-- Policy: Allow anonymous users to SELECT (read) scores
CREATE POLICY "Allow anonymous reads"
ON scores
FOR SELECT
TO anon
USING (true);

-- 5. Create index for better query performance
CREATE INDEX idx_scores_score ON scores(score DESC);
CREATE INDEX idx_scores_created_at ON scores(created_at DESC);

-- 6. Test the setup
SELECT '✅ Table created successfully' as status;

-- 7. Verify RLS policies
SELECT 
    schemaname,
    tablename,
    policyname,
    permissive,
    roles,
    cmd,
    qual,
    with_check
FROM pg_policies
WHERE tablename = 'scores';

-- ============================================
-- INSTRUCTIONS:
-- 1. Copy this entire script
-- 2. Go to Supabase Dashboard → SQL Editor
-- 3. Paste and Run the script
-- 4. Verify that you see "✅ Table created successfully"
-- 5. Check that 2 policies are listed:
--    - "Allow anonymous inserts"
--    - "Allow anonymous reads"
-- ============================================
