-- ============================================
-- SETUP TABEL LEADERBOARD DI SUPABASE
-- ============================================
-- Jalankan script ini di Supabase SQL Editor:
-- Dashboard → SQL Editor → New Query → Copy-paste script ini → Run

-- 1. Buat tabel scores dengan kolom avatar
CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name VARCHAR(100) NOT NULL,
    score INTEGER NOT NULL,
    streak INTEGER NOT NULL DEFAULT 0,
    avatar VARCHAR(50) DEFAULT '🏆',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Jika tabel sudah ada, tambahkan kolom avatar (abaikan jika sudah ada)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name='scores' 
        AND column_name='avatar'
    ) THEN
        ALTER TABLE scores ADD COLUMN avatar VARCHAR(50) DEFAULT '🏆';
    END IF;
END $$;

-- 2. Buat index untuk query lebih cepat
CREATE INDEX IF NOT EXISTS idx_scores_score ON scores(score DESC);
CREATE INDEX IF NOT EXISTS idx_scores_created_at ON scores(created_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

-- 4. Hapus policy yang sudah ada (jika ada)
DROP POLICY IF EXISTS "Allow public insert" ON scores;
DROP POLICY IF EXISTS "Allow public select" ON scores;

-- 5. Buat policy untuk INSERT (siapa saja bisa insert score)
CREATE POLICY "Allow public insert" ON scores
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- 6. Buat policy untuk SELECT (siapa saja bisa baca leaderboard)
CREATE POLICY "Allow public select" ON scores
    FOR SELECT
    TO anon
    USING (true);

-- 7. Verifikasi: Tampilkan struktur tabel
SELECT * FROM scores LIMIT 0;

-- ============================================
-- SELESAI! Tabel sudah siap digunakan
-- ============================================
